create table "user"
(
    user_id   uuid generated by default as identity
        primary key,
    email     VARCHAR(250) not null
        constraint user_pk
            unique,
    password  VARCHAR(250) not null,
    role      VARCHAR(20)  not null,
    createdAt timestamptz default now()
);

