INSERT INTO products (name, price, description, category_id) VALUES
('4K Webcam Pro', 109.00, 'Autofocus webcam with dual microphones for clear video meetings',
 (SELECT id FROM categories WHERE name = 'Electronics')),
('Bluetooth Speaker Mini', 49.95, 'Portable speaker with rich bass and 12-hour battery life',
 (SELECT id FROM categories WHERE name = 'Electronics')),
('Refactoring', 47.99, 'Practical techniques for improving existing code safely and incrementally',
 (SELECT id FROM categories WHERE name = 'Books')),
('The Pragmatic Programmer', 39.50, 'Career-defining software craftsmanship lessons for modern developers',
 (SELECT id FROM categories WHERE name = 'Books')),
('Classic Denim Jacket', 64.99, 'Comfortable mid-weight jacket with durable stitching for daily wear',
 (SELECT id FROM categories WHERE name = 'Clothing')),
('Performance Running Shorts', 28.50, 'Lightweight moisture-wicking shorts built for training and long runs',
 (SELECT id FROM categories WHERE name = 'Clothing')),
('Stainless Steel Kettle', 34.99, 'Fast-boiling electric kettle with automatic shutoff and cool handle',
 (SELECT id FROM categories WHERE name = 'Home')),
('Memory Foam Pillow', 42.00, 'Supportive pillow designed to reduce neck strain overnight',
 (SELECT id FROM categories WHERE name = 'Home')),
('Remote Control Stunt Car', 58.75, 'Rechargeable RC car that flips, spins, and handles rough surfaces',
 (SELECT id FROM categories WHERE name = 'Toys')),
('STEM Robotics Kit', 79.00, 'Hands-on kit teaching coding basics through interactive robot builds',
 (SELECT id FROM categories WHERE name = 'Toys')),
('Desk Reading Lamp', 31.49, 'Adjustable LED lamp with warm and cool brightness settings',
 (SELECT id FROM categories WHERE name = 'Home')),
('Clean Code', 41.20, 'Guidelines for writing maintainable, readable, and testable software',
 (SELECT id FROM categories WHERE name = 'Books'));
